apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # í…ŒìŠ¤íŠ¸ìš© -> ì‚­ì œ ê¸ˆì§€
          - path: /producer
            pathType: Prefix
            backend:
              service:
                name: producer-service
                port:
                  number: 80
          - path: /consumer
            pathType: Prefix
            backend:
              service:
                name: consumer-service
                port:
                  number: 80
          # ì‹¤ì„œë¹„ìŠ¤ìš©
          - path: /order
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 80
          - path: /restaurant
            pathType: Prefix
            backend:
              service:
                name: restaurant-service
                port:
                  number: 80
          - path: /ocr
            pathType: Prefix
            backend:
              service:
                name: ocr-service
                port:
                  number: 8080
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: ocr-service
                port:
                  number: 3002    # ğŸ”¥ ì¸ì¦ ìƒíƒœ ì„œë²„ ì™¸ë¶€ ì ‘ê·¼ìš© ingress ê²½ë¡œ
#          - path: /payment
#            pathType: Prefix
#            backend:
#              service:
#                name: payment-service
#                port:
#                  number: 80
#          - path: /auth
#            pathType: Prefix
#            backend:
#              service:
#                name: keycloak
#                port:
#                  number: 8080
